In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("data/preprocessed/Event_traces.csv")

In [3]:
failed_data = data[data["Label"] == "Fail"].drop_duplicates(subset=['Features'])
success_data = data[data["Label"] == "Success"].drop_duplicates(subset=['Features'])

In [4]:
failed_data["Features"] = failed_data["Features"].map(lambda x: x[1:-1].split(","))
success_data["Features"] = success_data["Features"].map(lambda x: x[1:-1].split(","))

In [5]:
failed_operation_count_unique = {}
failed_data["Features"].map(lambda x: [failed_operation_count_unique.update({op: failed_operation_count_unique.get(op, 0) + 1}) for op in set(x)])
success_operation_count_unique = {}
success_data["Features"].map(lambda x: [success_operation_count_unique.update({op: success_operation_count_unique.get(op, 0) + 1}) for op in set(x)])
print()

In [6]:
template = pd.read_csv("data/preprocessed/HDFS.log_templates.csv")

In [7]:
template["FailedCountUnique"] = template["EventId"].map(lambda x: failed_operation_count_unique.get(x, 0))
template["SuccessCountUnique"] = template["EventId"].map(lambda x: success_operation_count_unique.get(x, 0))

In [8]:
template
["E1", "E7", "E8", "E10", "E12", "E13", "E14", "E15", "E17", "E19", "E24", "E29"]
["E18?", "E20", "E27", "E28"]

,EventId,EventTemplate,FailedCountUnique,SuccessCountUnique
0,E1,[*]Adding an already existing block[*],5,0
1,E2,[*]Verification succeeded for[*],1412,7283
2,E3,[*]Served block[*]to[*],2636,12113
3,E4,[*]Got exception while serving[*]to[*],2273,11239
4,E5,[*]Receiving block[*]src:[*]dest:[*],4124,14259
5,E6,[*]Received block[*]src:[*]dest:[*]of size[*],2101,589
6,E7,[*]writeBlock[*]received exception[*],67,0
7,E8,[*]PacketResponder[*]for block[*]Interrupted[*],44,0
8,E9,[*]Received block[*]of size[*]from[*],4100,14259
9,E10,[*]PacketResponder[*]Exception[*],58,0
10,E11,[*]PacketResponder[*]for block[*]terminating[*],4117,14259
11,E12,[*]:Exception writing block[*]to mirror[*],26,0
12,E13,[*]Receiving empty packet for block[*],181,0
13,E14,[*]Exception in receiveBlock for block[*],54,0
14,E15,[*]Changing block file offset of block[*]from[...,38,0
15,E16,[*]:Transmitted block[*]to[*],2101,589
16,E17,[*]:Failed to transfer[*]to[*]got[*],8,0
17,E18,[*]Starting thread to transfer block[*]to[*],2122,590
18,E19,[*]Reopen Block[*],4,0
19,E20,[*]Unexpected error trying to delete block[*]B...,1379,152
20,E21,[*]Deleting block[*]file[*],4032,13691
21,E22,[*]BLOCK* NameSystem[*]allocateBlock:[*],4124,14259
22,E23,[*]BLOCK* NameSystem[*]delete:[*]is added to i...,3982,13247
23,E24,[*]BLOCK* Removing block[*]from neededReplicat...,4,0
24,E25,[*]BLOCK* ask[*]to replicate[*]to[*],2122,590
25,E26,[*]BLOCK* NameSystem[*]addStoredBlock: blockMa...,4100,14259
26,E27,[*]BLOCK* NameSystem[*]addStoredBlock: Redunda...,359,3
27,E28,[*]BLOCK* NameSystem[*]addStoredBlock: addStor...,499,12
28,E29,[*]PendingReplicationMonitor timed out block[*],37,0

In [9]:
data['Features'] = data['Features'].map(lambda x: x[1:-1].split(","))

In [10]:
len(data[data['Label'] == "Fail"])

16838

In [15]:
event_list = ['E1', 'E7', 'E8', 'E10', 'E12', 'E13', 'E14', 'E15', 'E17', 'E19', 'E24', 'E29']
event_list_weird = ['E27', 'E28']

event_list.extend(event_list_weird)

In [16]:
# Filter rows where EventId is NOT in the event_list
filtered_data = data[~data["Features"].map(lambda x: any([op for op in x if op in event_list]))]
filtered_data.shape

(568987, 6)

In [17]:
filtered_data['Label'].value_counts()

Label
Success    558208
Fail        10779
Name: count, dtype: int64

In [18]:
filtered_data_with_failed_events = data[data["Features"].map(lambda x: any([op for op in x if op in event_list]))]
filtered_data_with_failed_events.shape

(6074, 6)

In [ ]:
filtered_data_with_failed_events["Features"].map(lambda x: tuple(x)).unique()

293

In [46]:
filtered_data[filtered_data["Label"] == "Fail"]["Features"]

2         [E5, E22, E5, E5, E11, E9, E11, E9, E11, E9, E...
15        [E5, E22, E5, E5, E11, E9, E11, E9, E11, E9, E...
23        [E5, E5, E22, E5, E11, E9, E11, E9, E26, E26, ...
64        [E5, E5, E22, E5, E9, E11, E9, E26, E26, E11, ...
234       [E5, E22, E5, E5, E11, E9, E11, E9, E11, E9, E...
                                ...
573869    [E5, E5, E22, E5, E11, E9, E26, E11, E9, E11, ...
574077    [E5, E5, E5, E22, E11, E9, E11, E9, E11, E9, E...
574172    [E5, E5, E22, E5, E11, E9, E26, E25, E11, E9, ...
574900    [E5, E5, E5, E22, E11, E9, E11, E9, E11, E9, E...
575060    [E5, E5, E5, E22, E11, E9, E11, E9, E11, E9, E...
Name: Features, Length: 12993, dtype: object

In [47]:
data[data["Label"] == "Fail"]

,BlockId,Label,Type,Features,TimeInterval,Latency
2,blk_-3544583377289625738,Fail,21.0,"[E5, E22, E5, E5, E11, E9, E11, E9, E11, E9, E...","[0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...",3797
15,blk_-8531310335568756456,Fail,4.0,"[E5, E22, E5, E5, E11, E9, E11, E9, E11, E9, E...","[0.0, 2.0, 0.0, 56.0, 0.0, 0.0, 0.0, 0.0, 0.0,...",51107
23,blk_3947106522258141922,Fail,4.0,"[E5, E5, E22, E5, E11, E9, E11, E9, E26, E26, ...","[0.0, 0.0, 1.0, 27.0, 0.0, 0.0, 0.0, 0.0, 0.0,...",51509
64,blk_7956543127401791181,Fail,21.0,"[E5, E5, E22, E5, E9, E11, E9, E26, E26, E11, ...","[0.0, 0.0, 2.0, 49.0, 0.0, 0.0, 0.0, 0.0, 1.0,...",50560
91,blk_-3102267849859399193,Fail,16.0,"[E5, E5, E22, E7, E11, E10, E14, E7]","[0.0, 0.0, 60.0, 1.0, 0.0, 657.0, 0.0]",718
...,...,...,...,...,...,...
574651,blk_-8186558713608306359,Fail,7.0,"[E5, E22, E5, E5, E26, E13, E11, E9, E13, E11,...","[0.0, 1.0, 0.0, 11.0, 0.0, 0.0, 0.0, 0.0, 0.0,...",281
574900,blk_-1683688019270077407,Fail,1.0,"[E5, E5, E5, E22, E11, E9, E11, E9, E11, E9, E...","[0.0, 0.0, 0.0, 19.0, 0.0, 0.0, 0.0, 0.0, 0.0,...",237
574924,blk_3773788001864047190,Fail,7.0,"[E5, E5, E5, E22, E13, E11, E9, E13, E11, E9, ...","[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",262
575002,blk_1986112558741936483,Fail,7.0,"[E13, E5, E11, E9, E13, E5, E11, E9, E13, E5, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",200
575060,blk_-9128742458709757181,Fail,4.0,"[E5, E5, E5, E22, E11, E9, E11, E9, E11, E9, E...","[0.0, 0.0, 0.0, 10.0, 0.0, 0.0, 0.0, 0.0, 0.0,...",131